server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: localhost
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info 
  client:
    registerWithEureka: false
    fetchRegistry: false
logging:
  level:
    com.netflix.discovery: 'ON'
    org.springframework.cloud: 'DEBUG'

---
spring:
  profiles: docker

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka-server}
  client:
    prefer-ip-address: true
    registerWithEureka: false
    fetchRegistry: false
  
  
