server:
  url: http://localhost:${server.port}
  port: 51022
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: mp_authorizations
      host: localhost    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
psp:
  service: MP-PSPSERVICE
  
auth:
  service: MP-AUTHSERVER
  path: /oauth/token
  
oauth:
  client_id: mp_authorizations_client
  client_secret: Y2QgZWEgOWMgYzAgNzkgNDQgZGMgYjEgMDUgMTcgNjYgNWEgZDQgOGEgOTEg  
   
amqp:
  transactions:
    queue:
      authorization:
        created:
          request: authorization_created_request_queue

  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events     
          
  authorizations:
    exchange:
      completed:
        authorization: completed_authorization
      created:
        authorization: created_authorization

    queue:
      authorization:
        completed:
          response: authorization_completed_response_queue   

  exports:
    exchange:
      completed: 
         export-data: export_data
    queue:
      export:
        request: export_authorizations_request_queue
    key: EXPORT_AUTHORIZATIONS_REQUEST   

export:
  directory:
    output: workspace

---
spring:
  profiles: integration
  data:
    mongodb:
      database: mp_authorizations
      host: localhost
      port: 27018
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123      

server:
  url: http://o2c.ovh:${server.port}
  
export:
  directory:
    output: exportFiles  
    
---
spring:
  profiles: qa
  data:
    mongodb:
      database: mp_authorizations
      host: localhost
      port: 27018
  rabbitmq:
    host: localhost
    port: 5672
    username: master-pay
    password: master123      

server:
  url: http://qa.o2c.ovh:${server.port}
  
export:
  directory:
    output: exportFiles      
