server:
  url: http://localhost:${server.port}
  port: 51024
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: mp_balances
      host: localhost
      
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
   
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   
amqp:
  balances:
    exchange:
      created:
        balance: created_balance

    queue:
      combine:
        created:
          response: combine_created_balance_response_queue

  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events          

  exports:
    exchange:
      completed: 
         export-data: export_data
    queue:
      export:
        request: export_balances_request_queue
    key: EXPORT_BALANCES_REQUEST   

export:
  directory:
    output: workspace

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8880/validateClient
      
oauth:
  client_id: mp_balance_client
  client_secret: NDUgOGIgMDAgZTAgOWIgMDYgY2UgZTMgODQgNmMgM2YgN2YgZjUgNzEgYjkg

transaction:
  service: MP-TRANSACTIONS
  
beneficiary:
  service: MP-BENEFICIARIES
  
auth:
  service: MP-AUTHSERVER
  path: /oauth/token  
  
smoney:
  service: MP-MONEYPROVIDER

---
spring:
  profiles: integration
  data:
    mongodb:
      database: mp_balances
      host: localhost
      port: 27018
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123      
      
server:
  url: http://o2c.ovh:${server.port}

export:
  directory:
    output: exportFiles  

---
spring:
  profiles: qa
  data:
    mongodb:
      database: mp_balances
      host: localhost
      port: 27018
  rabbitmq:
    host: localhost
    port: 5672
    username: master-pay
    password: master123      
      
server:
  url: http://qa.o2c.ovh:${server.port}

export:
  directory:
    output: exportFiles  
