server:
  port: 51023
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    
param:
  service: MP-PARAMS
  
init-transaction:
  service: MP-INITTRANSACTIONS
  
auth:
  service: MP-AUTHSERVER
  path: /oauth/token   
  
oauth:
  client_id: mp_complete_client
  client_secret: MTIgYjQgOGMgYzEgMDcgOWUgOGIgMmQgNWMgMWYgODIgOTQgZDQgYmUgYWQg

amqp:
  complete-transactions:
    exchange:
      completed:
        transaction: completed_transaction
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events

---
spring:
  profiles: integration
  data:
    mongodb:
      database: mp_init_transactions
      host: localhost
      port: 27018
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123      


---
spring:
  profiles: qa
  data:
    mongodb:
      database: mp_init_transactions
      host: localhost
      port: 27018
  rabbitmq:
    host: localhost
    port: 5672
    username: master-pay
    password: master123      
