server:
  port: 51077
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    
authorizations:
  service: MP-AUTHORIZATIONS
  
captures:
  service: MP-CAPTURES
  
auth:
  service: MP-AUTHSERVER
  path: /oauth/token   
  
oauth:
  client_id: mp_payments_client
  client_secret: MGQgZTMgMmYgODcgZmUgZmUgYWMgOGEgNDMgNzcgMTQgZTYgODYgYzggOGIg
  
amqp:
  payments:
    exchange:
      completed:
        payment: completed_payment
        
    queue:
      payment:
        created:
          request: payment_created_request_queue
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events          
          
          
environment:
  nifi-url: http://localhost:60056
  callback-url: ${environment.nifi-url}/completePaymentCallback
  
---
spring:
  profiles: integration
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123


---
spring:
  profiles: qa
  rabbitmq:
    host: localhost
    port: 5672
    username: master-pay
    password: master123
