server:
  port: 51009
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: mp_params
      host: localhost
    
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
amqp:
  params:
    queue:
      payment-param-page:
        created:
          request: payment_param_page_response_queue
        updated:
          request: update_payment_param_page_response_queue    
          
          
---
spring:
  profiles: integration
  data:
    mongodb:
      database: mp_params
      host: localhost
      port: 27018
  rabbitmq:
    host: rabbitmq.o2c.ovh
    port: 5672
    username: master-pay
    password: master123      


---
spring:
  profiles: qa
  data:
    mongodb:
      database: mp_params
      host: localhost
      port: 27018
  rabbitmq:
    host: localhost
    port: 5672
    username: master-pay
    password: master123      
    
---
spring:
  profiles: docker 
  data:
    mongodb:
      host: ${MONGO_SERVER:o2c-mongodb}
      port: ${MONGO_PORT:27018}
  rabbitmq:
    host: ${RABBIT_SERVER:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_PASS}
    password: ${RABBITMQ_DEFAULT_USER}      
    
    
server: 
  port: ${PORT}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:eureka-server}:${EUREKA_PORT:8761}/eureka/
  instance:   
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true  
