server:
  port: 51074
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
      
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}


amqp:
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events

dalenys:
  url: https://secure-test.be2bill.com/front/service/rest/process    
  
---
spring:
  profiles: integration
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123    


---
spring:
  profiles: qa
  rabbitmq:
    host: localhost
    port: 5672
    username: master-pay
    password: master123    
